In [1]:
#seed pseudo random int
import numpy as np


In [ ]:
np.random.seed(seed=2)
a1=np.random.randint(10,size=(2,3))
a1

In [44]:
a1=np.random.randint(10,size=(3,3))
a1

array([[8, 1, 6],
       [9, 5, 1],
       [2, 4, 7]])

# seed doesn't changes the op values everytime 

In [45]:

randomarray=np.random.random((2,4))

In [46]:
randomarray

array([[0.97058031, 0.80025835, 0.60181712, 0.76495986],
       [0.16922545, 0.29302323, 0.52406688, 0.35662428]])

In [47]:
a1[:1]

array([[8, 1, 6]])

In [48]:
a1[:3]

array([[8, 1, 6],
       [9, 5, 1],
       [2, 4, 7]])

In [49]:
a1[:2]

array([[8, 1, 6],
       [9, 5, 1]])

In [50]:
a1[:]

array([[8, 1, 6],
       [9, 5, 1],
       [2, 4, 7]])

# manipulating & comparing arrays


# arithmetic operations

In [51]:
a1

array([[8, 1, 6],
       [9, 5, 1],
       [2, 4, 7]])

In [54]:
ones=np.ones(3)

In [56]:
ones 

array([1., 1., 1.])

In [57]:
ones * a1

array([[8., 1., 6.],
       [9., 5., 1.],
       [2., 4., 7.]])

In [58]:
a1 + a1

array([[16,  2, 12],
       [18, 10,  2],
       [ 4,  8, 14]])

In [59]:
a1 + ones

array([[ 9.,  2.,  7.],
       [10.,  6.,  2.],
       [ 3.,  5.,  8.]])

In [61]:
a2=np.array([[1,2,3],
           [2,3,54],
           [3,5,6]])

In [62]:
a2

array([[ 1,  2,  3],
       [ 2,  3, 54],
       [ 3,  5,  6]])

In [63]:
a1 // a2 #no decimal

array([[8, 0, 2],
       [4, 1, 0],
       [0, 0, 1]], dtype=int32)

In [64]:
a1 / a2  #returns decimals

array([[8.        , 0.5       , 2.        ],
       [4.5       , 1.66666667, 0.01851852],
       [0.66666667, 0.8       , 1.16666667]])

In [68]:
 a1 ** 2 #square

array([[64,  1, 36],
       [81, 25,  1],
       [ 4, 16, 49]], dtype=int32)

In [69]:
a1 ** 3 # cube

array([[512,   1, 216],
       [729, 125,   1],
       [  8,  64, 343]], dtype=int32)

In [71]:
a2 % 3 #remainder

array([[1, 2, 0],
       [2, 0, 0],
       [0, 2, 0]], dtype=int32)

In [72]:
a1  + a2 /2 #mean

array([[ 8.5,  2. ,  7.5],
       [10. ,  6.5, 28. ],
       [ 3.5,  6.5, 10. ]])