In [3]:
#Numpy is (numerical python) which is a backbone of Machine Learning 
#Turning the data into numericals
#NUMPY comes in data Analysis part in the framework
#Numpy functionalities are written in C which works faster compared to the Python list#N

In [4]:
import numpy as np
#ndarray is the main type of array

In [5]:
Numpyarray=np.array([1,2,3])

In [6]:
Numpyarray

array([1, 2, 3])

In [17]:
a1=np.array([[1,2,3],
    [3,4,5],
    [4,5,6]])

In [18]:
a1

array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6]])

In [9]:
a1.shape

(1, 3, 3)

In [27]:
a2=np.array([[[2.3,4,5],
             [4,5,7],
             [4,56.3,7]],
             
             [[2,3,4],
              [34,5,6],
              [3,5,6]]])

In [11]:
a1

array([[[1, 2, 3],
        [3, 4, 5],
        [4, 5, 6]]])

In [12]:
a2

array([[[ 2,  4,  5],
        [ 4,  5,  7],
        [ 4, 56,  7]],

       [[ 2,  3,  4],
        [34,  5,  6],
        [ 3,  5,  6]]])

In [19]:
a2.shape

(2, 3, 3)

In [20]:
a1.ndim

2

In [23]:
a2.ndim 

3

In [24]:
a1.ndim

2

In [26]:
#to check the datatype 
a1.dtype

dtype('int32')

In [28]:
a2.dtype

dtype('float64')

In [30]:
#size attribute is to check the no of elements in the array
a1.size,a2.size

(9, 18)

In [41]:
type(a1) #arrays were using is numpy is ndarray a universal dtype

numpy.ndarray

# creating  dataframe from a numpy array

In [38]:
import pandas as pd
df=pd.DataFrame(a1)

In [35]:
df

0  1  2
0  1  2  3
1  3  4  5
2  4  5  6

In [42]:
df2=pd.DataFrame(Numpyarray)

In [43]:
df2

0
0  1
1  2
2  3

In [44]:
type(df2)

pandas.core.frame.DataFrame

# Creating arrays

In [46]:
array1=np.array([1,2,3])
array1

array([1, 2, 3])

In [65]:
#ones attribute returns a new array as per given shape filled with ONES 1
C=np.ones((2,3,3))
C

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [70]:
C.dtype

dtype('float64')

In [69]:
type(C)

numpy.ndarray

In [74]:
D=np.zeros((3,3,4))
D

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [79]:
range2=np.arange(0,20,2) #start end step
range2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [88]:
#we want numpy to fill the array with random int
random=np.random.randint(1,10,size=(3,4)) #rows,coloumns
random.size

12

In [89]:
random

array([[1, 2, 4, 1],
       [2, 1, 1, 1],
       [1, 5, 8, 1]])

In [90]:
random.shape

(3, 4)

In [92]:
random.dtype

dtype('int32')

In [95]:
np.random.random((2,4)) #Return the elements of half interval i.e 0 to 1

array([[0.06348423, 0.96623068, 0.14247445, 0.81188828],
       [0.94650259, 0.64449492, 0.83468837, 0.05964732]])