# Aggregation 
performing same operations on multiple or no of things

In [1]:
import numpy as np
a1=np.array([1,2,3])

In [2]:
a1

array([1, 2, 3])

In [3]:
a2=np.array([2,5,7])
a2

array([2, 5, 7])

In [4]:
sum(a1)

6

In [5]:
#creating a massive array to demonstrate how fast numpy is

In [6]:
massive=np.random.random(10000)

In [7]:
massive[:100]

array([0.81524699, 0.57838454, 0.15202141, 0.81740537, 0.23233301,
       0.21808001, 0.94981664, 0.71374698, 0.88831191, 0.15478782,
       0.98728071, 0.2235188 , 0.91896091, 0.12969879, 0.77156213,
       0.7175129 , 0.00561452, 0.52699948, 0.32703863, 0.51844094,
       0.74074831, 0.66742713, 0.27789759, 0.17825787, 0.85778152,
       0.81607473, 0.437016  , 0.4677154 , 0.00319164, 0.12358236,
       0.70634507, 0.50653091, 0.34703294, 0.19435089, 0.02606081,
       0.6625367 , 0.05840355, 0.30047745, 0.87522303, 0.89567705,
       0.71755735, 0.489501  , 0.78893111, 0.5424332 , 0.25427711,
       0.30792861, 0.3406045 , 0.05939913, 0.57191296, 0.11316936,
       0.71459682, 0.25102873, 0.05124157, 0.273173  , 0.60239552,
       0.66303328, 0.98000075, 0.33164522, 0.24099394, 0.96850097,
       0.00304668, 0.25179778, 0.26969453, 0.40887991, 0.70598573,
       0.08894101, 0.46478199, 0.18670681, 0.57962273, 0.65432375,
       0.76552827, 0.47400199, 0.57956408, 0.92297137, 0.63458

In [8]:
%timeit sum(massive) #for pythons sum()

1.27 ms ± 122 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [9]:
%timeit np.sum(massive) #for numpy array

7.78 µs ± 446 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [10]:
np.var(a2)

4.222222222222222

In [11]:
#standard deviation is square root of variance
np.std(a2)

2.0548046676563256

In [12]:
np.min(a2)

2

In [13]:
np.max(a2)

7

In [14]:
np.var(a2)

4.222222222222222

In [15]:
np.std(a2)

2.0548046676563256

In [16]:
np.sqrt(np.var(a2)) #square root of variance is standard deviation

2.0548046676563256

# Manipulating (reshaping numpy arrays)

In [17]:
a1= np.array([[[1,2,3],
    [2,34,4],
    [2,3,4]],
              [[2,3,4],
              [3,4,5],
              [3,45,6]]])

In [18]:
a1

array([[[ 1,  2,  3],
        [ 2, 34,  4],
        [ 2,  3,  4]],

       [[ 2,  3,  4],
        [ 3,  4,  5],
        [ 3, 45,  6]]])

In [19]:
a1.shape

(2, 3, 3)

In [20]:
a1.T.shape #transpose

(3, 3, 2)

# Dot product
multiplication of 2 matrices is called dot product where multiplying matrix with single num is "scalar multiplication"

In [21]:
mat1= np.random.randint(10,size=(3,3))
mat2= np.random.randint(10,size=(3,2))
mat1,mat2


(array([[3, 0, 5],
        [4, 9, 3],
        [3, 1, 1]]),
 array([[9, 7],
        [5, 7],
        [1, 4]]))

In [22]:
#ELEMENT WISE MUL IS KNOWN AS HARDAMARD PRODUCT

In [23]:
mat3=np.dot(mat1,mat2)

In [24]:
mat3.shape

(3, 2)

In [25]:
mat3.T


array([[ 32,  84,  33],
       [ 41, 103,  32]])

In [27]:
mat3.T.shape


(2, 3)