# salesDataFrame

In [36]:
import numpy as np
import pandas as pd

In [77]:
sales=np.random.randint(12,size=(4,4))

In [78]:
sales

array([[ 9,  1,  4,  0],
       [ 0,  8,  0,  7],
       [ 7,  5,  3,  7],
       [ 7, 11,  0,  1]])

In [124]:
sales_Dataframe=pd.DataFrame(sales.reshape(5,4),index=["Mon","Tues","wed","Thurs","Fri"],columns=["Shawarma","Paneer","roti","Burger"])

ValueError: cannot reshape array of size 16 into shape (5,4)

In [83]:
sales_Dataframe

Shawarma  Paneer  roti  Burger
Mon           4       4     2       0
Tues         10       2    11       8
wed           8       7     2      10
Thurs         6       1     7       5
Fri           5      10     9       7

In [84]:
item=np.array([100,40,15,50])

In [85]:
item

array([100,  40,  15,  50])

In [86]:
item_price=pd.DataFrame(item.reshape(1,4),index=["price"],columns=["Shawarma","Paneer","roti","Burger"])

In [87]:
item_price

Shawarma  Paneer  roti  Burger
price       100      40    15      50

In [88]:
#dot product of the sales and price dataframe

In [112]:
item_price.shape

(1, 4)

In [113]:
sales_Dataframe.shape

(5, 5)

In [114]:
#item_price=item_price.T


In [118]:
Total

Mon  Tues   wed  Thurs   Fri
price  590  1645  1610    995  1385

In [119]:
sales_Dataframe

Shawarma  Paneer  roti  Burger  Total($)
Mon           4       4     2       0       590
Tues         10       2    11       8      1645
wed           8       7     2      10      1610
Thurs         6       1     7       5       995
Fri           5      10     9       7      1385

In [120]:
item_price

Shawarma  Paneer  roti  Burger
price       100      40    15      50

In [121]:
#if dot product doesnt work transpose the matrix from row to coloumn
Total

Mon  Tues   wed  Thurs   Fri
price  590  1645  1610    995  1385

In [122]:
sales_Dataframe["Total($)"]= Total.T

In [123]:
sales_Dataframe

Shawarma  Paneer  roti  Burger  Total($)
Mon           4       4     2       0       590
Tues         10       2    11       8      1645
wed           8       7     2      10      1610
Thurs         6       1     7       5       995
Fri           5      10     9       7      1385

# Comparision operators

In [126]:
a1=np.array([1,2,3])
a1

array([1, 2, 3])

In [130]:
a2=np.array([[2,2,3],
           [1,2,3]])

In [131]:
a2 > a1

array([[ True, False, False],
       [False, False, False]])

In [133]:
a1>a2

array([[False, False, False],
       [False, False, False]])

In [135]:
a1<=a2

array([[ True,  True,  True],
       [ True,  True,  True]])

In [136]:
a2<=a1

array([[False,  True,  True],
       [ True,  True,  True]])

In [137]:
a2>=a1

array([[ True,  True,  True],
       [ True,  True,  True]])

In [145]:
array2 = a1>=a2

In [150]:
#operators are boolean data types 
type(array2),array2.dtype

(numpy.ndarray, dtype('bool'))

In [ ]:
dd